---
apiVersion: v1
kind: Pod
metadata:
  name: poc-calendar
  labels:
    app: web
spec:
  containers:
    - name: front-end
      image: eu.gcr.io/supervision-187414/poc-calendar:v1beta3
      ports:
        - containerPort: 80
      imagePullPolicy: Always
